baseurl: /mock
orgname: 'BundleKind (mock)'
collections:
  non_profits:
    state: ''
    city: ''
    output: true
    permalink: /:path
defaults:
  - scope:
      path: ''
      type: non_profits
    values:
      layout: non_profit
prose:
  rooturl: ""
  siteurl: 'http://bundlekind.github.io/mock/'
  media: 'assets/media'
  ignore:
    - index.html
    - _config.yml
    - .gitignore
    - Gemfile
    - /_layouts
    - /_data
    - /assets
  metadata:
    _non_profits:
      - name: "layout"
        field:
          element: "hidden"
          value: "non_profit"
      - name: "name"
        field:
          element: "text"
          value: "Name"
          placeholder: "nonprofit name"
      - name: "ein"
        field:
          element: "text"
          value: "EIN number"
          placeholder: "the nonprofit's employer ID number"
      - name: "homepage"
        field:
          element: "text"
          value: "URL"
          placeholder: "homepage URL"
      - name: "description"
        field:
          element: "text"
          value: "description"
          placeholder: "short description"
      - name: "address"
        field:
          element: "text"
          value: "address"
          placeholder: "full address"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Modify Tags"
          placeholder: "Choose Tags"
          options:
            - name: "addiction"
              value: "addiction"
            - name: "advocacy"
              value: "advocacy"
            - name: "arts"
              value: "arts"
            - name: "charitable"
              value: "charitable"
            - name: "education"
              value: "education"
            - name: "elderly"
              value: "elderly"
            - name: "employment"
              value: "employment"
            - name: "family"
              value: "family"
            - name: "funding"
              value: "funding"
            - name: "greek"
              value: "greek"
            - name: "health"
              value: "health"
            - name: "media"
              value: "media"
            - name: "military"
              value: "military"
            - name: "poverty"
              value: "poverty"
            - name: "professional"
              value: "professional"
            - name: "rehabilitation"
              value: "rehabilitation"
            - name: "religious"
              value: "religious"
            - name: "social"
              value: "social"
            - name: "sports"
              value: "sports"
            - name: "technology"
              value: "technology"
            - name: "farm"
              value: "farm"
            - name: "gender"
              value: "gender"
            - name: "nature"
              value: "nature"
            - name: "politics"
              value: "politics"
            - name: "women"
              value: "women"
            - name: "youth"
              value: "youth"
